repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        name: ruff (fix all except E501)
        args: [ "--fix", "--ignore", "E501" ]
      - id: ruff-format
        name: ruff-format
      - id: ruff
        name: ruff (E501 only; fail leftovers)
        args: [ "--select", "E501" ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy http_py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: unittests
        name: unittests
        entry: poetry run python -m unittest discover -v
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-push]
